export const videoJson = [
  {
    id: 1,
    url: "https://github.yuanhau.com/authly/videos/dlv7.mp4",
    liked: false,
    saved: false,
    current: true,
  },
  {
    id: 2,
    url: "https://github.yuanhau.com/authly/videos/dlv1.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 3,
    url: "https://github.yuanhau.com/authly/videos/dlv2.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 4,
    url: "https://github.yuanhau.com/authly/videos/dlv3.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 5,
    url: "https://github.yuanhau.com/authly/videos/dlv4.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 6,
    url: "https://github.yuanhau.com/authly/videos/dlv5.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 7,
    url: "https://github.yuanhau.com/authly/videos/dlv6.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 8,
    url: "https://github.yuanhau.com/authly/videos/dlv7.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 9,
    url: "https://github.yuanhau.com/authly/videos/dlv8.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 10,
    url: "https://github.yuanhau.com/authly/videos/dlv9.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 11,
    url: "https://github.yuanhau.com/authly/videos/dlv10.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 12,
    url: "https://github.yuanhau.com/authly/videos/dlv11.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 13,
    url: "https://github.yuanhau.com/authly/videos/dlv12.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 14,
    url: "https://github.yuanhau.com/authly/videos/dlv13.mp4",
    liked: false,
    saved: false,
    current: false,
  },
];

export const videoJson2 = [
  {
    id: 1,
    url: "https://github.yuanhau.com/authly/videos/dlv7.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 2,
    url: "https://github.yuanhau.com/authly/videos/dlv1.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 3,
    url: "https://github.yuanhau.com/authly/videos/dlv2.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 4,
    url: "https://github.yuanhau.com/authly/videos/dlv3.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 5,
    url: "https://github.yuanhau.com/authly/videos/dlv4.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 6,
    url: "https://github.yuanhau.com/authly/videos/dlv5.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 7,
    url: "https://github.yuanhau.com/authly/videos/dlv6.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 8,
    url: "https://github.yuanhau.com/authly/videos/dlv7.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 9,
    url: "https://github.yuanhau.com/authly/videos/dlv8.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 10,
    url: "https://github.yuanhau.com/authly/videos/dlv9.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 11,
    url: "https://github.yuanhau.com/authly/videos/dlv10.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 12,
    url: "https://github.yuanhau.com/authly/videos/dlv11.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 13,
    url: "https://github.yuanhau.com/authly/videos/dlv12.mp4",
    liked: false,
    saved: false,
    current: false,
  },
  {
    id: 14,
    url: "https://github.yuanhau.com/authly/videos/dlv13.mp4",
    liked: false,
    saved: false,
    current: false,
  },
];
